name: Maven Central Release

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: NHSUOP

      - name: Prepare GPG Key
        run: |
          # Private key ko runner ke GPG keyring mein manual import karna
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import --no-tty

      - name: Publish to Maven Central
        run: mvn clean deploy -B -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.NHSUOP }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}